import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Topbar from "@/components/other/topbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BookFace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Topbar/>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
